import {
  ArrowLeft,
  ArrowRight,
  Check,
  Code,
  Folder,
  Layers,
  Menu,
  Moon,
  Network,
  Search,
  Settings,
  Sun,
  X,
  Monitor,
  ChevronRight,
  BookOpen,
  Circle,
  CircleDashed,
  CirclePause,
  CircleCheck,
  CircleHelp,
  LockKeyhole,
  FolderOpen,
  ArrowUpRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  MoonStar,
  SunMedium,
  LogOut,
  DoorOpen,
  LayoutGrid,
  PanelsTopLeft,
  ScanSearch,
  CircleX,
} from 'lucide'
import {
  ArrowLeft as StaticArrowLeft,
  ArrowRight as StaticArrowRight,
  Check as StaticCheck,
  Code as StaticCode,
  Folder as StaticFolder,
  Layers as StaticLayers,
  Menu as StaticMenu,
  Moon as StaticMoon,
  Network as StaticNetwork,
  Search as StaticSearch,
  Settings as StaticSettings,
  Sun as StaticSun,
  X as StaticX,
  Monitor as StaticMonitor,
  ChevronRight as StaticChevronRight,
  BookOpen as StaticBookOpen,
  Circle as StaticCircle,
  CircleDashed as StaticCircleDashed,
  CirclePause as StaticCirclePause,
  CircleCheck as StaticCircleCheck,
  CircleHelp as StaticCircleHelp,
  LockKeyhole as StaticLockKeyhole,
  FolderOpen as StaticFolderOpen,
  ArrowUpRight as StaticArrowUpRight,
  ChevronLeft as StaticChevronLeft,
  ChevronDown as StaticChevronDown,
  ChevronUp as StaticChevronUp,
  MoonStar as StaticMoonStar,
  SunMedium as StaticSunMedium,
  LogOut as StaticLogOut,
  DoorOpen as StaticDoorOpen,
  LayoutGrid as StaticLayoutGrid,
  PanelsTopLeft as StaticPanelsTopLeft,
  ScanSearch as StaticScanSearch,
  CircleX as StaticCircleX,
} from '@lucide/vue'

export const icons = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  check: Check,
  code: Code,
  folder: Folder,
  layers: Layers,
  menu: Menu,
  moon: Moon,
  network: Network,
  search: Search,
  settings: Settings,
  sun: Sun,
  x: X,
  monitor: Monitor,
  'chevron-right': ChevronRight,
  book: BookOpen,
  circle: Circle,
  'circle-dashed': CircleDashed,
  'circle-pause': CirclePause,
  'circle-check': CircleCheck,
  'circle-help': CircleHelp,
  lock: LockKeyhole,
  'folder-open': FolderOpen,
  'arrow-up-right': ArrowUpRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'moon-star': MoonStar,
  'sun-medium': SunMedium,
  'log-out': LogOut,
  'door-open': DoorOpen,
  'layout-grid': LayoutGrid,
  panels: PanelsTopLeft,
  'scan-search': ScanSearch,
  'circle-x': CircleX,
}
export type IconName = keyof typeof icons
export const staticIcons = {
  'arrow-left': StaticArrowLeft,
  'arrow-right': StaticArrowRight,
  check: StaticCheck,
  code: StaticCode,
  folder: StaticFolder,
  layers: StaticLayers,
  menu: StaticMenu,
  moon: StaticMoon,
  network: StaticNetwork,
  search: StaticSearch,
  settings: StaticSettings,
  sun: StaticSun,
  x: StaticX,
  monitor: StaticMonitor,
  'chevron-right': StaticChevronRight,
  book: StaticBookOpen,
  circle: StaticCircle,
  'circle-dashed': StaticCircleDashed,
  'circle-pause': StaticCirclePause,
  'circle-check': StaticCircleCheck,
  'circle-help': StaticCircleHelp,
  lock: StaticLockKeyhole,
  'folder-open': StaticFolderOpen,
  'arrow-up-right': StaticArrowUpRight,
  'chevron-left': StaticChevronLeft,
  'chevron-down': StaticChevronDown,
  'chevron-up': StaticChevronUp,
  'moon-star': StaticMoonStar,
  'sun-medium': StaticSunMedium,
  'log-out': StaticLogOut,
  'door-open': StaticDoorOpen,
  'layout-grid': StaticLayoutGrid,
  panels: StaticPanelsTopLeft,
  'scan-search': StaticScanSearch,
  'circle-x': StaticCircleX,
} satisfies Record<IconName, unknown>
