import {
  ArrowLeft,
  ArrowRight,
  Check,
  Code,
  Folder,
  Layers,
  Menu,
  Moon,
  Network,
  Search,
  Settings,
  Sun,
  X,
  Monitor,
  ChevronRight,
  BookOpen,
} from 'lucide'
import {
  ArrowLeft as StaticArrowLeft,
  ArrowRight as StaticArrowRight,
  Check as StaticCheck,
  Code as StaticCode,
  Folder as StaticFolder,
  Layers as StaticLayers,
  Menu as StaticMenu,
  Moon as StaticMoon,
  Network as StaticNetwork,
  Search as StaticSearch,
  Settings as StaticSettings,
  Sun as StaticSun,
  X as StaticX,
  Monitor as StaticMonitor,
  ChevronRight as StaticChevronRight,
  BookOpen as StaticBookOpen,
} from '@lucide/vue'

export const icons = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  check: Check,
  code: Code,
  folder: Folder,
  layers: Layers,
  menu: Menu,
  moon: Moon,
  network: Network,
  search: Search,
  settings: Settings,
  sun: Sun,
  x: X,
  monitor: Monitor,
  'chevron-right': ChevronRight,
  book: BookOpen,
}
export type IconName = keyof typeof icons
export const staticIcons = {
  'arrow-left': StaticArrowLeft,
  'arrow-right': StaticArrowRight,
  check: StaticCheck,
  code: StaticCode,
  folder: StaticFolder,
  layers: StaticLayers,
  menu: StaticMenu,
  moon: StaticMoon,
  network: StaticNetwork,
  search: StaticSearch,
  settings: StaticSettings,
  sun: StaticSun,
  x: StaticX,
  monitor: StaticMonitor,
  'chevron-right': StaticChevronRight,
  book: StaticBookOpen,
} satisfies Record<IconName, unknown>
